### ISSUE TITLE
Display all the information related to only one particular football team (team name, stadium name, seating capacity, location, conference, division, surface type, stadium roof type, star player). Do not display information related to the other NFL teams.

### ISSUE THREAD

**Issue by wuwukennywu** [wuwukennywu/LetsPlayFootball#11]
As a fan, I would like to view all information for a given football team.

Size: 3

Estimate: Sprint 1

Definition of Done:
- Code produced adheres to the coding standard (Refer to coding standard on GitHub)
- Code commented/documented (Doxygen)
- Code checked into source control system (GitHub)
- All associated team information is displayed correctly.
- List of assumptions/tasks are implemented.
- Peer reviewed and approved by the Product Owner
- Testing passed (Refer to Test part of the agile story)
- Get feedback and be approved by Product Owner

List of Assumptions:
- displayTeam window exists
- Main window exists
- Database reflects information correctly

Tasks:
- Read database information and display correct information for a selected team.
- Ability to select what team’s information is displayed.

Tests:
- Check to ensure information from other teams is not displayed.
- Check to ensure the information for the selected team is correct.

**Comment by wuwukennywu** [comment]
Code needs to be commented/documented

**Comment by wuwukennywu** [comment]
Feedback from Jerry: User should not be able to add in their specific input. program should do it itself so no error handling should be used.

Code has been fixed:
- No more line edit
-- Replaced with combo box
-- Combo box repopulates every time you enter displayWindow with the current teams in the database
- Once team is picked; display only shows that specific team.

**Comment by OverworldLord** [comment]
Reviewed and Approved

**Comment by thea-k** [comment]
tested and approved
