### ISSUE TITLE
Provide the capability to add a new team and its corresponding information by having your program read from an input file given to the class (assume the team has the default souvenirs)

### ISSUE THREAD

**Issue by wuwukennywu** [wuwukennywu/LetsPlayFootball#12]
As a administrator I want to add a team record to the team information table in the SQL database and Map data structure.

Priority: High

Size: 13

Estimate: Sprint 2

Definition of done:
- Code produced adheres to the coding standard (Refer to coding standard on GitHub)
- Code commented/documented (Doxygen)
- Code checked into source control system (GitHub)
- Team information (team record, distance, and souvenir list) is added to the SQL database/Map data structure
-- Desk check by comparing input information with the information within the SQL database/Map data structure after addition
- Peer reviewed and approved by Scrum Master AND Product Owner

List of assumption/tasks are implemented:
- AdminWindow UI
- Testing passed (Refer to Test part of the agile story)
- Get feedback and be approved by customer
- List of assumptions
- UI is able to submit text file
- Program is able to add team record into SQL database/Map data structure
- Traversing through the program is functional
- UI is in theme of the program (NFL)

Task:
- Input for team information
- Button to add team record/distance/souvenir to the SQL database
- Error check if the same team information is already added to the database/Map data structure
- If addition failed
-- Output a failed message box
-- Clear input
- If addition is successful
-- Output a success message box
-- Clear input
- Functionality to go back to main menu
-- Back button to go to main menu
- Once team record is added; Map data structure is re-populated to be used for the program
- Functionality to add a input file to (re)populate the Map data structure with the team information/souvenir list and the SQL database

Test: (Passed if only test passes for both windows and mac)
- Click on back button to check if window redirects to administrator window
- Check what happens if you add in the same team information twice
-- Outputs an error message
-- Clears input
- Check buttons to see if the team record/distance/souvenir list is added to the SQL database
- Output the Map data structure and see if the team record is added
- Desk check by comparing input information with the addition of the data to the database

**Comment by wuwukennywu** [comment]
Revision of story;
- No manual input
- File input ONLY
- When adding a new team; souvenir default items should be added
- Souvenir items should be error handled (duplicates)
- Teams should be error handled (duplicates)

**Comment by wuwukennywu** [comment]
Story is technically done
- Implement a ordered OR unordered map to store information as well

**Comment by wuwukennywu** [comment]
Implemented add team distance txt file
Implemented add team souvenir txt file

**Comment by wuwukennywu** [comment]
Error handling:
Will skip duplicate souvenir items/teams/distances

**Comment by thea-k** [comment]
Tested to ensure all information(souvenir and distance as well) is read in correctly from a file

**Comment by wuwukennywu** [comment]
FIXED invalid team file error handling

**Comment by OverworldLord** [comment]
Reviewed and Approved.

**Comment by wuwukennywu** [comment]
Map Data structure implementation pushed to Sprint 2
UI Theme (NFL) pushed to Sprint 2
