### ISSUE TITLE
Provide the capability to change the prices of the traditional souvenirs

### ISSUE THREAD

**Issue by wuwukennywu** [wuwukennywu/LetsPlayFootball#13]
As an administrator I want to have the ability to modify the price of a traditional souvenir of a team.

Size: 3

Estimate: Sprint 1

Definition of done:
- Code produced adheres to the coding standard (Refer to coding standard on GitHub)
- Code commented/documented (Doxygen)
- Code checked into source control system (GitHub)
- Team information is modified to the team table in the SQL database
-- Desk check by comparing input stadium and or capacity information with the information within the SQL database
- List of assumption/tasks are implemented
- Peer reviewed and approved by a Peer AND Product Owner
- Testing passed (Refer to Test part of the agile story)
- Get feedback and be approved by customer

List of assumptions:
- UI is able to modify souvenir information
- Admin window exists
- modifySouvenir exists
- Program is able to modify the price of the specified souvenir
- Traversing through the program is functional

Task:
- ModifyTeam UI
- Input for team stadium and or capacity information
- Submit button to modify price of the souvenir record to the SQL database
- Error check if the team information modification is already added to the database
- If modification failed
-- Output a failed message box
-- Clear input
- If modification is successful
-- Output a success message box
-- Clear input
- Functionality to go back to main menu
-- Back button to go to main menu

Test: (Passed if only test passes for both windows and mac)
- Click on back button to check if window redirects to administrator window
- Check what happens if you leave the input to modify empty
-- Outputs an error message
-- Clears input
- Check submit button to see if the souvenir record is modified to the SQL database
- Desk check by comparing input information with the modification of the data to the database

**Comment by wuwukennywu** [comment]
Story is implemented/done

**Comment by OverworldLord** [comment]
tested and approved.

**Comment by thea-k** [comment]
tested and approved
