### ISSUE TITLE
Display the list of the NFL teams sorted by team name.

### ISSUE THREAD

**Issue by OverworldLord** [wuwukennywu/LetsPlayFootball#14]
As a fan, I would like to view all information for a every football team.

Priority: High

Size: 3

Estimate: Sprint 1

Definition of Done:
- Code produced adheres to the coding standard (Refer to coding standard on GitHub)
- Code commented/documented (Doxygen)
- Code checked into source control system (GitHub)
- All associated team information is displayed correctly.
- List of assumptions/tasks are implemented.
- Peer reviewed and approved by the Product Owner
- Testing passed (Refer to Test part of the agile story)
- Get feedback and be approved by Product Owner

List of Assumptions:
- Main window exists
- Database reflects information correctly

Tasks:
- Read database information and display correct information for every team.
- Ability to refresh the display

Tests:
- Check to ensure the information for every team is correct.
- Desk check by comparing displayed information with the data from the SQL database

**Comment by wuwukennywu** [comment]
Code still needs to be commented/documented

**Comment by thea-k** [comment]
Completed display for stadium roof type, sorted by stadium name

**Comment by OverworldLord** [comment]
Reviewed and Approved

**Comment by thea-k** [comment]
tested and approved
