### ISSUE TITLE
Provide the capability to add new traditional souvenirs

### ISSUE THREAD

**Issue by wuwukennywu** [wuwukennywu/LetsPlayFootball#20]

**Comment by wuwukennywu** [comment]
Story is done and ready to be reviewed/tested

**Comment by wuwukennywu** [comment]
Error handling:
- Duplicate souvenirs for each team (individual teams)
- Input is empty

**Comment by thea-k** [comment]
Tested for error handling (can't input duplicate souvenirs, empty input not taken) & information remains persistent

**Comment by OverworldLord** [comment]
Reviewed and approved
