### ISSUE TITLE
Provide the ability to modify stadium information including capacity if a team moves into a new stadium. (administrator only) (The Los Angeles Rams are planning to move to Farmers Field in 2019)

### ISSUE THREAD

**Issue by wuwukennywu** [wuwukennywu/LetsPlayFootball#27]
As an administrator I want to modify a team's stadium information in case they wish to move into a new stadium and or expand. 

Size: 5

Estimate: Sprint 1

Definition of done:
- Code produced adheres to the coding standard (Refer to coding standard on GitHub)
- Code commented/documented (Doxygen)
- Code checked into source control system (GitHub)
- Team Information record is modified and saved to the SQL database
-- Desk check by comparing input information with the information within the SQL database
- Peer reviewed and approved by a Peer AND Product Owner

List of assumption/tasks are implemented:
- AdminWindow UI
- modifyTeamInfo UI
- Testing passed (Refer to Test part of the agile story)
- Get feedback and be approved by customer
- List of assumptions
- UI is able to modify a team record information
- Program is able to add souvenir record into SQL database
- Traversing through the program is functional

Task:
- Input for which team to modify their information
- Button to update the team information record to the SQL database
- Error check if the input is empty
- If modification failed
-- Output a failed message box
-- Clear input
- If modification is successful
-- Output a success message box
-- Clear input
- Functionality to go back to main menu
-- Back button to go to main menu

Test: (Passed if only test passes for both windows and mac)
- Click on back button to check if window redirects to administrator window
- Check what happens if you modify the wrong input for a variable with restrictions (division, conference, roof type, surface type, etc)
-- Outputs an error message
-- Clears input
- Check buttons to see if the souvenir record is added to the SQL database
- Desk check by comparing input information with the modification of the data from the database

**Comment by wuwukennywu** [comment]
Story is done

**Comment by OverworldLord** [comment]
Tested and Approved

**Comment by thea-k** [comment]
Tested and Approved
minor suggestion- add ability to do City Name, State when changing location
