### ISSUE TITLE
List and display the count of the number of NFL team whose surface type is Bermuda Grass.

### ISSUE THREAD

**Issue by wuwukennywu** [wuwukennywu/LetsPlayFootball#29]
As a fan I want to see all the NFL teams who uses a specified surface type for their stadiums, I also want to see how many of them use Bermuda grass.

Size: 3

Estimate: Sprint 1

Definition of done:
- Code produced adheres to the coding standard (Refer to coding standard on GitHub)
- Code commented/documented (Doxygen)
- Code checked into source control system (GitHub)
- Display shows the specified stadiums with their surface type
- UI displays a counter for Bermuda grass.
-- Desk check by comparing stadium information from SQL database with what is displayed in the program
- List of assumption/tasks are implemented
- Peer reviewed and approved by a Peer AND Product Owner
- Testing passed (Refer to Test part of the agile story)
- Get feedback and be approved by customer

List of assumptions:
- UI is able take in user input for specified surface type
- mainWindow exists
- displayStadium exists
- Window displays the stadiums with the surface type specified
- Traversing through the program is functional

Task:
- displayStadium UI
- Input for surface type
- Display button to show the specified stadium and their surface type
- Error check by desk checking display info with SQL database info
- Functionality to go back to main menu
-- Back button to go to main menu

Test: (Passed if only test passes for both windows and mac)
- Click on back button to check if window redirects to administrator window
- Check what happens if you leave the input to display empty
-- Outputs an error message
-- Clears input
- Desk check by comparing displayed information with the database

**Comment by wuwukennywu** [comment]
Story is done and ready to be reviewed/tested

**Comment by thea-k** [comment]
tested and approved
