### ISSUE TITLE
Button to change display order of teams to sort by conference

### ISSUE THREAD

**Issue by codenameCodename** [wuwukennywu/LetsPlayFootball#38]
As a fan, I want to display the teams in order by conference

Size: 3

Estimate: Sprint 1

Definition of Done:
Code produced adheres to the coding standard (Refer to coding standard on GitHub)
Code commented/documented (Doxygen)
Code checked into source control system (GitHub)
Information for all souvenirs displays correctly upon opening window.
Upon pressing button, all teams sort by conference.
List of assumptions/tasks are implemented.
Peer reviewed and approved by a peer and product owner
Testing passed (Refer to Test part of the agile story)

List of Assumptions:
Main window exists
UI is in theme of the program
Database exists

Tasks:
Read database information and display correct information for each team.
Button to change order list is displayed.

Tests:
Check to ensure information from other teams is not displayed.
Check to ensure the information for the selected team is correct.

**Comment by wuwukennywu** [comment]
Create the agile story

**Comment by wuwukennywu** [comment]
Comment your author box above the method in the header file (did it for you)

**Comment by wuwukennywu** [comment]
will be pushed back because agile story is not done

**Comment by wuwukennywu** [comment]
Reviewed and approved

**Comment by OverworldLord** [comment]
Reviewed and approved
