### ISSUE TITLE
Display souvenirs and display souvenirs by team

### ISSUE THREAD

**Issue by codenameCodename** [wuwukennywu/LetsPlayFootball#39]
As a fan, I want to view the list of souvenirs of one particular team.

Size: 3

Estimate: Sprint 1

Definition of Done:

Code produced adheres to the coding standard (Refer to coding standard on GitHub)
Code commented/documented (Doxygen)
Code checked into source control system (GitHub)
Information for all souvenirs displays correctly upon opening window.
Upon selecting team, all of that teams's souvenirs' information displays.
List of assumptions/tasks are implemented.
Peer reviewed and approved by a peer and product owner
Testing passed (Refer to Test part of the agile story)

List of Assumptions:
Main window exists
UI is in theme of the program
Database exists

Tasks:

Lay out souvenir window
Read database information and display correct information for each team.
Ability to select which team's souvenir list information is displayed.

Tests:
Check to ensure information from other teams is not displayed.
Check to ensure the information for the selected team is correct.

**Comment by wuwukennywu** [comment]
Create the agile story please

**Comment by wuwukennywu** [comment]
Comment your author box above the method in the header file (did it for you)

**Comment by wuwukennywu** [comment]
Will be pushed backed because agile story is not done

**Comment by wuwukennywu** [comment]
Reviewed and approved

**Comment by OverworldLord** [comment]
Reviewed and approved
