### ISSUE TITLE
User Order - Provide the capability for a football fan to plan his/her dream vacation by allowing a football fan to choose their starting team and all the other teams they would like to visit using the order specified.  Display the total distance traveled.

### ISSUE THREAD

**Issue by wuwukennywu** [wuwukennywu/LetsPlayFootball#43]
As a fan I want to travel to my selected teams by the order I selected them through and showing me the total distance I traveled.

Size: 3

Estimate: Sprint 3

Definition of done:
- Code produced adheres to the coding standard (Refer to coding standard on GitHub)
- Code commented/documented (Doxygen)
- Code checked into source control system (GitHub)
- Calculates the order of stadium travels by user order and outputs the total distance traveled
-- Desk check by comparing a manual calculation from the map given to us (stadiums traveled and total distance)
- List of assumption/tasks are implemented
- Peer reviewed and approved by a Peer AND Product Owner
- Testing passed (Refer to Test part of the agile story)
- Get feedback and be approved by customer

List of assumptions:
- UI is able to receive input (stadiums) from the user
- Display order in console
- Souvenir window exists
- Display total distance in souvenir window

Task:
- Perform the calculations (user order list/total distance)
- Error check if the information is wrong (desk check by manual calculation)

Test: (Passed if only test passes for both windows and mac)
- Make sure the list is cleared after every trip
- Display is cleared after every trip calculation
- Desk check by comparing output from console and ui to the manual desk check of using Dijkstra's

**Comment by wuwukennywu** [comment]
Pushed back to sprint 3

**Comment by wuwukennywu** [comment]
Taking over this story

**Comment by wuwukennywu** [comment]
Finished/Implemented in Qt

**Comment by thea-k** [comment]
desk checked and reviewed

**Comment by OverworldLord** [comment]
Reviewed and approved
