### ISSUE TITLE
Determine the minimum spanning tree (MST) connecting all the NFL stadiums using Prim’s or Kruskal’s algorithm. Display the associated mileage.

### ISSUE THREAD

**Issue by wuwukennywu** [wuwukennywu/LetsPlayFootball#46]

**Comment by thea-k** [comment]
As a fan, I want to be able to perform a MST starting at the State Farm Stadium that takes the shortest distance, displaying associated mileage when complete.

Size: 3

Estimate: Sprint 3

Definition of Done:
Code produced adheres to the coding standard (Refer to coding standard on GitHub)
Code commented/documented (Doxygen)
Code checked into source control system (GitHub)
Information for all souvenirs displays correctly upon opening window.
Upon pressing button, a MST is performed (updating associated mileage).
List of assumptions/tasks are implemented.
Peer reviewed and approved by a peer and product owner
Testing passed (Refer to Test part of the agile story)

List of Assumptions:
Main window exists
UI is in theme of the program
Database exists
Teams are present within database
Graph is well connected

Tasks:
Read database information and display correct MST mileage after travel is complete.
Output loaded edges to console.
Output discovery edges to console.

Tests:
Desk check to ensure all information is correct and accurate.

**Comment by thea-k** [comment]
Checked to make sure extended distance file works with MST; desk checked to make sure the new distance is added correctly by the MST.

**Comment by OverworldLord** [comment]
UI fixed.

**Comment by OverworldLord** [comment]
Reviewed and Approved.
