### ISSUE TITLE
Perform a DFS starting at the Minnesota Vikings.  If there is a choice, always choose the shortest distance.  Display the associated mileage.

### ISSUE THREAD

**Issue by wuwukennywu** [wuwukennywu/LetsPlayFootball#47]
As a fan, I want to be able to perform a DFS starting at the Minnesota Vikings that takes the shortest distance, displaying associated mileage when complete.

Size: 3

Estimate: Sprint 1

Definition of Done:
Code produced adheres to the coding standard (Refer to coding standard on GitHub)
Code commented/documented (Doxygen)
Code checked into source control system (GitHub)
Information for all souvenirs displays correctly upon opening window.
Upon pressing button, a DFS is performed (updating associated mileage).
List of assumptions/tasks are implemented.
Peer reviewed and approved by a peer and product owner
Testing passed (Refer to Test part of the agile story)

List of Assumptions:
Main window exists
UI is in theme of the program
Database exists
Teams are present within database
Graph is well connected

Tasks:
Read database information and display correct DFS mileage after travel is complete.
Output discovery edges to console.
Output back edges to console.

Tests:
Desk check to ensure all information is correct and accurate.

**Comment by OverworldLord** [comment]
Reviewed and approved

**Comment by wuwukennywu** [comment]
incorrectly uploaded files (files are not in the qt folder/build folder but are found outside of it).

do not forget to clean the project before uploading

**Comment by OverworldLord** [comment]
Fixed issues with erroneous file path

**Comment by codenameCodename** [comment]
I wanna ask Jerry about the output for bfs and dfs output. It doesn't seem right that it only outputs the total distance

**Comment by wuwukennywu** [comment]
Jerry would like us to pick the best DFS

**Comment by wuwukennywu** [comment]
Requires a desk check
- before AND after inserting edges from San Diego Sailors stadium (extension)

**Comment by OverworldLord** [comment]
Desk check performed

**Comment by OverworldLord** [comment]
Wrong place to say so; your DC was for  BFS, not DFS
