### ISSUE TITLE
SHOPPING CART: A football fan can purchase multiple souvenirs. Your Agile team must keep track of the number of souvenirs purchased at each stadium. Display the total amount spent at each stadium and a grand total for all stadiums visited

### ISSUE THREAD

**Issue by wuwukennywu** [wuwukennywu/LetsPlayFootball#49]
As a fan, I want to be able to purchase multiple souvenirs. I also want to see a total per stadium and a grand total of how many souvenirs I purchased and how much it cost.

Size: 3

Estimate: Sprint 1

Definition of Done:
Code produced adheres to the coding standard (Refer to coding standard on GitHub)
Code commented/documented (Doxygen)
Code checked into source control system (GitHub)
Information for all souvenirs displays correctly upon opening window.
Souvenirs can be added for purchase, a total per stadium and grand total are displayed accurately.
List of assumptions/tasks are implemented.
Peer reviewed and approved by a peer and product owner
Testing passed (Refer to Test part of the agile story)

List of Assumptions:
Main window exists
UI is in theme of the program
Database exists
Teams are selected for travel

Tasks:
Read database information and display correct information for souvenir.
Allow the user to add souvenirs to the correct team and stadium.
Add souvenir being purchased to shoppingCart database

Tests:
Check to ensure information from other team are not modified.
Check to ensure the information for the selected team is correct.
Check to ensure items are being added correctly.
Check to ensure that items are being added to the correct team and stadium.

**Comment by OverworldLord** [comment]
Done, requires commenting

**Comment by OverworldLord** [comment]
Added comments

**Comment by OverworldLord** [comment]
Product owner approved

**Comment by wuwukennywu** [comment]
Peer Reviewed - Passed
