### ISSUE TITLE
UI DESIGN: CUSTOM TRIP

### ISSUE THREAD

**Issue by wuwukennywu** [wuwukennywu/LetsPlayFootball#50]
As a fan I want to be able to select the starting team and the teams that I wish to visit for my trip in the program.

Size: 3

Estimate: Sprint 2

Definition of done:
- Code produced adheres to the coding standard (Refer to coding standard on GitHub)
- Code commented/documented (Doxygen)
- Code checked into source control system (GitHub)
- UI is implemented and allows the user to select their starting team, teams to visit, and which algorithm is chosen.
-- Desk check by comparing the displayed teams in the combo box and listWidget to the information from the SQL database
- List of assumption/tasks are implemented
- Peer reviewed and approved by Peer AND Product Owner

List of Assumptions:
- Main Window UI
- Testing passed (Refer to Test part of the agile story)
- Get feedback and be approved by customer
- List of assumptions
- UI is able to track and take in user input (teams selected/starting city)
- Program is connected to the SQL database
- Program calculates (with the selected algorithm) on order of visitations

Task:
- Input for starting team and selected team visitation
-- Selected teams are check marked
- Button to add all teams for visitation
-- Starting team isn't listed in team selection
-- Selected teams are cleared and unchecked
- Functionality to go back to main menu
-- Back button to go to main menu
- In the souvenir window, it should display the team in order (based on chosen algorithm)

Test: (Passed if only test passes for both windows and mac)
- Click on back button to check if window redirects to main window
- Error check if no teams are selected
- Error check once selected team is changed, the list should displays accordingly
- Check if next buttons goes to the souvenir purchase window
- Desk check listWidget team names with the data from the Excel sheet (team names)
- Desk check the starting team combo box with the data from the Excel sheet (team names)

**Comment by wuwukennywu** [comment]
Max thinks there will be a huge pitfall

**Comment by wuwukennywu** [comment]
done

**Comment by OverworldLord** [comment]
Reviewed and approved

**Comment by thea-k** [comment]
reviewed and approved
