### ISSUE TITLE
Login Authentication

### ISSUE THREAD

**Issue by wuwukennywu** [wuwukennywu/LetsPlayFootball#6]
As an administrator, I want to authenticate my login information to have administrative privileges.

Size: 3

Estimate: Sprint 1

Definition of done:
- Code produced adheres to the coding standard (Refer to coding standard on GitHub)
- Code commented/documented (Doxygen)
- Code checked into source control system (GitHub)
- Login information is able to be authenticated
-- Desk check by comparing login information with the login information within the SQL database
- List of assumption/tasks are implemented
- Peer reviewed and approved by a Peer and Product Owner
- Testing passed (Refer to Test part of the agile story)
- Get feedback and be approved by customer

List of assumptions:
- Main window exists
- UI of login exists
- Admin is able to submit login information
- Program is able to authenticate login information
- Traversing through the program is functional

Task:
- Input for login information
- Submit button to authenticate login information
- If authentication failed
-- Output a failed message box
-- Clear input
- If authentication is successful
-- Output a success message box
-- Redirect to administrator window
- Functionality to go back to main menu
-- Back button to go to main menu

Test: (Passed if only test passes for both windows and mac)
- Click on back button to check if window redirects to main window
- Administrator is able to input their login information
- Program is able to authenticate login information (true/false)
- Check for failure; input wrong login information
- Check for success; input correct login information
- Desk check login information with stored login information from SQL database

**Comment by wuwukennywu** [comment]
Story is done

Waiting for approval:
Another developer
Program Owner (Mason)

**Comment by wuwukennywu** [comment]
Bugs
- to bypass restriction after 3 failed attempts, user can just go back and forth from windows to allow login attempts again.

- Have to make the counter variable a global if you wish to count the attempts throughout program use

**Comment by OverworldLord** [comment]
Bugs - User can make infinite 'failed attempts' without being locked out, regardless of changing windows

**Comment by OverworldLord** [comment]
Reviewed and Approved.

**Comment by thea-k** [comment]
tested and approved
